#!/usr/bin/env python3
"""
csv_to_latex.py
---------------
Converts the survey models CSV into a LaTeX longtable, split into
OCR-Dependent and OCR-Free sections (based on the 'OCR' column).

The table is wrapped in \resizebox{\linewidth}{!}{...} so it always
fits the page width, shrinking the font as needed.

Model names are rendered as:  ModelName~(\citeyear{bibtex_key})
which shows just the year as a hyperlink in the compiled PDF.

Usage:
    python3 csv_to_latex.py [input.csv] [output.tex]

Defaults:
    input  → models_table.csv
    output → models_table.tex
"""

import re
import sys
import pandas as pd

# ── CLI args ──────────────────────────────────────────────────────────────────
INPUT_CSV  = sys.argv[1] if len(sys.argv) > 1 else "models_table.csv"
OUTPUT_TEX = sys.argv[2] if len(sys.argv) > 2 else "models_table.tex"

# ── Column display config ─────────────────────────────────────────────────────
# Each entry: (csv_column, header_text, column_spec)
# p{Xcm} columns wrap text; adjust widths to taste.
COLUMNS = [
    ("Name",               r"Model",           r"l"),
    ("Venue",              r"Venue",            r"l"),
    ("Downstream Task",    r"Tasks",            r"p{2.8cm}"),
    ("Input Doc Mod.",     r"Doc.~Mod.",        r"c"),
    ("Prompt Mod.",        r"Prompt~Mod.",      r"c"),
    ("Vision Encoder",     r"Vision Encoder",   r"p{2.8cm}"),
    ("LLM/MLLM",          r"LLM/MLLM",         r"p{3.0cm}"),
    ("Prompt Strategies",  r"Prompt Strat.",    r"c"),
    ("RAG Strategies",     r"RAG Strat.",       r"c"),
    ("Agentic",            r"Agentic",          r"c"),
]

def escape_latex(val):
    """Escape special LaTeX characters in a cell value."""
    if pd.isna(val):
        return "--"
    val = str(val).strip()
    for char, repl in [
        ("\\", r"\textbackslash{}"),
        ("&",  r"\&"),
        ("%",  r"\%"),
        ("$",  r"\$"),
        ("#",  r"\#"),
        ("_",  r"\_"),
        ("{",  r"\{"),
        ("}",  r"\}"),
        ("~",  r"\textasciitilde{}"),
        ("^",  r"\textasciicircum{}"),
    ]:
        val = val.replace(char, repl)
    return val if val else "--"

def extract_year(bibtex_key):
    """Pull a 4-digit year out of a bibtex key, e.g. 'wang2025foo' → '2025'."""
    m = re.search(r"(20\d{2}|19\d{2})", bibtex_key)
    return m.group(1) if m else None

def make_model_cell(row):
    """
    Format:  \textbf{Name}~(\citeyear{key})
    \citeyear requires natbib or biblatex; it prints just the year as a link.
    Falls back to \cite{key} if no year can be extracted.
    """
    name   = escape_latex(row["Name"])
    bibtex = str(row["Bibtex"]).strip() if pd.notna(row["Bibtex"]) else ""
    if not bibtex:
        return rf"\textbf{{{name}}}"
    year = extract_year(bibtex)
    if year:
        return rf"\textbf{{{name}}}~(\citeyear{{{bibtex}}})"
    return rf"\textbf{{{name}}}~\cite{{{bibtex}}}"

def build_table_rows(df):
    lines = []
    for _, row in df.iterrows():
        cells = []
        for col, _, _ in COLUMNS:
            if col == "Name":
                cells.append(make_model_cell(row))
            else:
                cells.append(escape_latex(row.get(col, "")))
        lines.append("  " + " & ".join(cells) + r" \\")
    return "\n".join(lines)

def main():
    df = pd.read_csv(INPUT_CSV)

    required = {"OCR", "Name"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"CSV is missing columns: {missing}")

    df["_ocr_flag"] = df["OCR"].str.strip().str.lower()
    df_dep  = df[df["_ocr_flag"] == "yes"].copy()
    df_free = df[df["_ocr_flag"] == "no"].copy()

    col_spec    = "|".join(spec for _, _, spec in COLUMNS)
    col_headers = " & ".join(
        rf"\textbf{{{hdr}}}" for _, hdr, _ in COLUMNS
    )
    n_cols = len(COLUMNS)
    section_span = rf"\multicolumn{{{n_cols}}}{{|l|}}"

    latex = rf"""% ─────────────────────────────────────────────────────────────────────────────
% Auto-generated by csv_to_latex.py — do NOT edit manually.
% Re-generate:  python3 csv_to_latex.py models_table.csv models_table.tex
%
% Required packages (add to your preamble):
%   \usepackage{{booktabs}}
%   \usepackage{{longtable}}
%   \usepackage{{array}}
%   \usepackage{{xcolor}}
%   \usepackage{{colortbl}}
%   \usepackage{{caption}}
%   \usepackage{{adjustbox}}   % for \begin{{adjustbox}}
%   \usepackage{{natbib}}      % for \citeyear  (or use biblatex)
%   \usepackage{{lscape}}      % optional: landscape
% ─────────────────────────────────────────────────────────────────────────────

\definecolor{{sectionbg}}{{gray}}{{0.88}}

% \begin{{landscape}}   % ← uncomment for landscape orientation
\begin{{table}}[htbp]
\centering
\caption{{Survey of VRDU models, split by OCR dependency.
  \textbf{{Doc.~Mod.}} = document modality accepted by the model;
  \textbf{{Prompt~Mod.}} = modality of the input prompt;
  \textbf{{T}} = text, \textbf{{V}} = visual/image, \textbf{{L}} = layout.
  `--' indicates not reported.}}
\label{{tab:model_survey}}
\begin{{adjustbox}}{{max width=\linewidth}}
\begin{{tabular}}{{{col_spec}}}
\toprule
{col_headers} \\
\midrule

% ── OCR-Dependent ─────────────────────────────────────────────────────────────
\rowcolor{{sectionbg}}
{section_span}{{\textbf{{OCR-Dependent}}}} \\
\midrule
{build_table_rows(df_dep)}
\midrule[0.4pt]

% ── OCR-Free ──────────────────────────────────────────────────────────────────
\rowcolor{{sectionbg}}
{section_span}{{\textbf{{OCR-Free}}}} \\
\midrule
{build_table_rows(df_free)}

\bottomrule
\end{{tabular}}
\end{{adjustbox}}
\end{{table}}
% \end{{landscape}}   % ← uncomment if you used landscape above
"""

    with open(OUTPUT_TEX, "w", encoding="utf-8") as f:
        f.write(latex)

    print(f"✓  Wrote {OUTPUT_TEX}  ({len(df_dep)} OCR-Dependent, {len(df_free)} OCR-Free rows)")

if __name__ == "__main__":
    main()