#!/usr/bin/env python3
r"""
summary_tables_convert.py
-----------------
Converts the survey models CSV into two LaTeX tables:
  1. Grouped by architecture category ('Approach' column), with OCR column visible.
  2. Grouped by OCR dependency ('OCR' column), with Architecture column visible.

The OCR column may contain values like 'Yes*' or 'No*', where the asterisk
indicates optional or partial OCR usage.  When grouping by OCR the asterisk
is stripped from the group label but preserved as a $^*$ superscript on the
model name so the distinction is not lost.

Usage:
    python3 summary_tables_convert.py [input.csv] [output.tex]

Defaults:
    input  → models_summary.csv
    output → models_summary.tex
"""

import re
import sys
from pathlib import Path
import pandas as pd

# ── CLI args ──────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent
INPUT_CSV   = sys.argv[1] if len(sys.argv) > 1 else str(BASE_DIR / "models_summary.csv")
_out_base   = sys.argv[2] if len(sys.argv) > 2 else str(BASE_DIR / "models_summary")
_out_base   = _out_base[:-4] if _out_base.endswith(".tex") else _out_base
OUTPUT_ARCH = _out_base + "_arch.tex"
OUTPUT_OCR  = _out_base + "_ocr.tex"

DISPLAY_NAME_MAP = {
    "Name": "Model",
    "Model": "Model",
    "Architecture": "Architecture",
    "OCR": "OCR",
    "Downstream Tasks": "Tasks",
    "Prompt Strategy": "Prompt",
    "Prompting Strategy": "Prompt",
    "Search Strategy": "Search",
    "Agentic Strategy": "Agentic",
    "Modality": "Mod.",
}

COLUMN_SPEC_MAP = {
    "Name": "l",
    "Model": "l",
    "Venue": "l",
    "Architecture": "l",
    "OCR": "c",
    "Downstream Tasks": "l",
    "Modality": "c",
    "Vision Encoder": "l",
    "LLM Backbone": "l",
    "Prompt Strategy": "c",
    "Prompting Strategy": "c",
    "Search Strategy": "c",
    "Agentic Strategy": "c",
}

# Columns always hidden regardless of grouping mode
ALWAYS_HIDDEN = {"ID", "Bibtex"}

PREFERRED_ORDER = [
    "Model",
    "Name",
    "Venue",
    "OCR",
    "Architecture",
    "Vision Encoder",
    "LLM Backbone",
    "Modality",
    "Prompting Strategy",
    "Prompt Strategy",
    "Search Strategy",
    "Agentic Strategy",
    "Downstream Tasks",
]

ARCH_GROUP_ORDER = [
    "Hierarchical Document Transformer",
    "Backbone-Centric MLLM Adaptation",
    "Retriever-Generator",
    "Agentic Pipeline",
]

OCR_GROUP_ORDER = ["No", "Yes"]
OCR_SORT_ORDER = ["No", "No*", "Yes", "Yes*"]

# Abbreviations for the Architecture column when shown inside the OCR table.
ARCH_ABBREVS = {
    "Hierarchical Document Transformer": "HDT",
    "Backbone-Centric MLLM Adaptation":  "BC",
    "Retriever-Generator":                "RAG",
    "Agentic Pipeline":                   "AP",
}

ARCH_SORT_RANK = {value: idx for idx, value in enumerate(ARCH_GROUP_ORDER)}
OCR_SORT_RANK = {value: idx for idx, value in enumerate(OCR_SORT_ORDER)}

PREAMBLE = r"""% ─────────────────────────────────────────────────────────────────────────────
% Auto-generated by summary_tables_convert.py — do NOT edit manually.
% Re-generate:  python3 summary_tables_convert.py models_summary.csv models_summary.tex
%
% Required packages (add to your preamble):
%   \usepackage{booktabs}
%   \usepackage{longtable}
%   \usepackage{array}
%   \usepackage{xcolor}
%   \usepackage{colortbl}
%   \usepackage{caption}
%   \usepackage{adjustbox}   % for \begin{adjustbox}
%   \usepackage{natbib}      % for \citeyear  (or use biblatex)
%   \usepackage{lscape}      % optional: landscape
% ─────────────────────────────────────────────────────────────────────────────

\definecolor{sectionbg}{gray}{0.88}

"""


def first_present(columns, candidates):
    """Return the first candidate column present in the DataFrame."""
    for candidate in candidates:
        if candidate in columns:
            return candidate
    return None


def make_column_config(df_columns, hidden_cols):
    """Infer the displayed columns, labels, and column specs from the CSV."""
    visible = [col for col in df_columns if col not in hidden_cols]
    ordered = [col for col in PREFERRED_ORDER if col in visible]
    ordered.extend(col for col in visible if col not in ordered)
    return [
        (col, DISPLAY_NAME_MAP.get(col, col), COLUMN_SPEC_MAP.get(col, "l"))
        for col in ordered
    ]


def escape_latex(val):
    """Escape special LaTeX characters in a cell value."""
    if pd.isna(val):
        return "--"
    val = str(val).strip()
    for char, repl in [
        ("\\", r"\textbackslash{}"),
        ("&",  r"\&"),
        ("%",  r"\%"),
        ("$",  r"\$"),
        ("#",  r"\#"),
        ("_",  r"\_"),
        ("{",  r"\{"),
        ("}",  r"\}"),
        ("~",  r"\textasciitilde{}"),
        ("^",  r"\textasciicircum{}"),
    ]:
        val = val.replace(char, repl)
    return val if val else "--"


def extract_year(bibtex_key):
    """Pull a 4-digit year out of a bibtex key, e.g. 'wang2025foo' → '2025'."""
    m = re.search(r"(20\d{2}|19\d{2})", bibtex_key)
    return m.group(1) if m else None


def make_model_cell(row, model_col, has_asterisk=False):
    r"""
    Format:  \textbf{Name}~(\citeyear{key})
    If has_asterisk is True, appends $^*$ superscript to the name.
    \citeyear requires natbib or biblatex; it prints just the year as a link.
    Falls back to \cite{key} if no year can be extracted.
    """
    name = escape_latex(row[model_col])
    if has_asterisk:
        name = name + r"$^*$"
    bibtex = str(row["Bibtex"]).strip() if pd.notna(row["Bibtex"]) else ""
    if not bibtex:
        return rf"{{{name}}}"
    year = extract_year(bibtex)
    if year:
        return rf"{{{name}}}~(\citeyear{{{bibtex}}})"
    return rf"{{{name}}}~\cite{{{bibtex}}}"


def build_table_rows(df, columns, model_col, asterisk_col=None, cell_value_maps=None):
    """Render all data rows as LaTeX table row strings.

    cell_value_maps: optional dict mapping column_name -> {raw_value -> display_value}
    """
    lines = []
    for _, row in df.iterrows():
        has_asterisk = False
        if asterisk_col and pd.notna(row.get(asterisk_col)):
            has_asterisk = str(row[asterisk_col]).strip().endswith("*")
        cells = []
        for col, _, _ in columns:
            if col == model_col:
                cells.append(make_model_cell(row, model_col, has_asterisk))
            else:
                raw = row.get(col, "")
                if cell_value_maps and col in cell_value_maps and pd.notna(raw):
                    raw = cell_value_maps[col].get(str(raw).strip(), str(raw).strip())
                cells.append(escape_latex(raw))
        lines.append("  " + " & ".join(cells) + r" \\")
    return "\n".join(lines)


def add_secondary_sort_keys(df, sort_col, model_col, ocr_sort_col=None):
    """Add stable sort keys for sorting rows inside each rendered group."""
    work_df = df.copy()
    unknown_rank = max(len(ARCH_SORT_RANK), len(OCR_SORT_RANK)) + 1

    if sort_col == "OCR":
        work_df["_secondary_sort"] = (
            work_df[sort_col]
            .fillna("")
            .astype(str)
            .str.strip()
            .map(OCR_SORT_RANK)
            .fillna(unknown_rank)
        )
    elif sort_col:
        work_df["_secondary_sort"] = (
            work_df[sort_col]
            .fillna("")
            .astype(str)
            .str.strip()
            .map(ARCH_SORT_RANK)
            .fillna(unknown_rank)
        )
    else:
        work_df["_secondary_sort"] = 0

    if ocr_sort_col:
        work_df["_ocr_sort"] = (
            work_df[ocr_sort_col]
            .fillna("")
            .astype(str)
            .str.strip()
            .map(OCR_SORT_RANK)
            .fillna(unknown_rank)
        )
    else:
        work_df["_ocr_sort"] = 0

    work_df["_model_sort"] = work_df[model_col].fillna("").astype(str).str.lower()
    return work_df.sort_values(
        by=["_group", "_secondary_sort", "_ocr_sort", "_model_sort"],
        kind="stable",
    )


def build_single_table(df, group_col, group_order_list, hidden_cols,
                        model_col, asterisk_col, caption, label,
                        cell_value_maps=None, secondary_sort_col=None,
                        ocr_sort_col=None):
    """Build a complete LaTeX table block as a string."""
    columns = make_column_config(df.columns, hidden_cols)
    col_spec = " ".join(spec for _, _, spec in columns)
    col_headers = " & ".join(rf"\textbf{{{hdr}}}" for _, hdr, _ in columns)
    n_cols = len(columns)
    section_span = rf"\multicolumn{{{n_cols}}}{{l}}"

    work_df = df.copy()
    work_df["_group"] = (
        work_df[group_col].fillna("Uncategorized").astype(str).str.strip()
    )
    if group_col == "OCR":
        work_df["_group"] = work_df["_group"].str.rstrip("*")

    work_df = add_secondary_sort_keys(
        work_df,
        sort_col=secondary_sort_col,
        model_col=model_col,
        ocr_sort_col=ocr_sort_col,
    )

    seen_groups = list(dict.fromkeys(work_df["_group"].tolist()))
    ordered_groups = [g for g in group_order_list if g in seen_groups]
    ordered_groups.extend(g for g in seen_groups if g not in ordered_groups)

    section_lines = []
    for idx, group in enumerate(ordered_groups):
        group_df = work_df[work_df["_group"] == group].copy()
        if group_df.empty:
            continue
        if idx > 0:
            section_lines.append(r"\midrule[0.4pt]")
            section_lines.append("")
        section_lines.append(
            rf"% ── {group} ─────────────────────────────────────────────────────────────"
        )
        section_lines.append(r"\rowcolor{sectionbg}")
        section_lines.append(
            rf"{section_span}{{\textbf{{{escape_latex(group)}}}}} \\"
        )
        section_lines.append(r"\midrule")
        section_lines.append(
            build_table_rows(group_df, columns, model_col, asterisk_col, cell_value_maps)
        )
        section_lines.append("")

    section_block = "\n".join(section_lines).rstrip()

    table_lines = [
        rf"% ── {label} ──────────────────────────────────────────────────────────────",
        r"\begin{table*}[t]",
        r"\centering",
        r"% \small",
        r"\scriptsize",
        r"\captionsetup{font=small}",
        r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{0.86}",
        rf"\begin{{adjustbox}}{{width=\textwidth}}",
        rf"\begin{{tabular}}{{{col_spec}}}",
        r"\toprule",
        rf"{col_headers} \\",
        r"\midrule",
        "",
        section_block,
        "",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{adjustbox}",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\end{table*}",
        "",
    ]
    return "\n".join(table_lines)


def main():
    df = pd.read_csv(INPUT_CSV)

    model_col = first_present(df.columns, ["Model", "Name"])
    group_col = first_present(df.columns, ["Architecture", "Approach"])
    ocr_col = "OCR" if "OCR" in df.columns else None

    required = {"Bibtex"}
    missing = required - set(df.columns)
    if not model_col:
        missing.add("Model/Name")
    if not group_col:
        missing.add("Architecture/Approach")
    if missing:
        raise ValueError(f"CSV is missing columns: {sorted(missing)}")

    # ── Table 1: Grouped by Architecture (OCR column visible) ─────────────────
    # No asterisk on model names here — the OCR column itself shows 'Yes*'/'No*'.
    arch_hidden = ALWAYS_HIDDEN | {group_col}
    arch_caption = (
        r"Survey of VRDU models grouped by architecture category. "
        r"\textbf{Mod.}: input modality (T\,=\,text, V\,=\,visual, L\,=\,layout). "
        r"\textbf{OCR}: OCR used at inference."
        r"(Yes\,=\,required; No\,=\, not required; "
        r"Yes\textsuperscript{*}\,=\, not OCR dependent; "
        r"No\textsuperscript{*}\,=\, OCR-derived training, no OCR at inference. "
        r"\textbf{Search}: search strategy "
        r"(Dense, Sparse, Joint\,=\,both). "
        r"\textbf{Prompt}: prompting strategy "
        r"(CoT\,=\,Chain of Thought; ReAct\,=\,Reason\,+\,Act). "
        r"\textbf{Agentic}: agentic workflow type "
        r"(Open\,=\,open-ended iterative; Fixed\,=\,fixed iterative). "
        r"`--' indicates not reported."
    )
    arch_table = build_single_table(
        df, group_col, ARCH_GROUP_ORDER,
        arch_hidden, model_col,
        asterisk_col=None,
        caption=arch_caption,
        label="tab:model_survey_arch",
        secondary_sort_col=ocr_col,
        ocr_sort_col=ocr_col,
    )

    with open(OUTPUT_ARCH, "w", encoding="utf-8") as f:
        f.write(PREAMBLE)
        f.write(arch_table)
    print(f"✓  Wrote {OUTPUT_ARCH}  ({len(df)} rows, architecture-grouped)")

    # ── Table 2: Grouped by OCR dependency (Architecture column visible) ──────
    # Architecture values are abbreviated; models with Yes*/No* get $^*$ on name.
    if ocr_col:
        ocr_hidden = ALWAYS_HIDDEN | {ocr_col}
        ocr_caption = (
            r"Survey of VRDU models grouped by OCR dependency. "
            r"Groups: \textbf{Yes}\,=\,OCR required at inference; "
            r"\textbf{No}\,=\,OCR not required at inference. "
            r"$^*$\,next to a model name has group-dependent meaning: "
            r"\textbf{Yes\textsuperscript{*}}\,=\,model is not strictly OCR-dependent "
            r"but incorporates OCR as a framework component; "
            r"\textbf{No\textsuperscript{*}}\,=\,OCR was used explicitly during training "
            r"but is not required at inference. "
            r"\textbf{Architecture} abbreviations: "
            r"HDT\,=\,Hierarchical Document Transformer; "
            r"BC\,=\,Backbone-Centric MLLM Adaptation; "
            r"Search\,=\,Retriever-Generator; AP\,=\,Agentic Pipeline. "
            r"\textbf{Mod.}: input modality (T\,=\,text, V\,=\,visual, L\,=\,layout). "
            r"\textbf{Search Strat.}: retrieval strategy "
            r"(Dense, Sparse, Joint\,=\,both). "
            r"\textbf{Prompt Strat.}: prompting strategy "
            r"(CoT\,=\,Chain of Thought; ReAct\,=\,Reason\,+\,Act). "
            r"\textbf{Agentic}: agentic workflow type "
            r"(Open\,=\,open-ended tool use; Fixed\,=\,fixed pipeline). "
            r"`--' indicates not reported."
        )
        ocr_table = build_single_table(
            df, ocr_col, OCR_GROUP_ORDER,
            ocr_hidden, model_col,
            asterisk_col=ocr_col,
            caption=ocr_caption,
            label="tab:model_survey_ocr",
            cell_value_maps={group_col: ARCH_ABBREVS},
            secondary_sort_col=group_col,
            ocr_sort_col=ocr_col,
        )
        with open(OUTPUT_OCR, "w", encoding="utf-8") as f:
            f.write(PREAMBLE)
            f.write(ocr_table)
        print(f"✓  Wrote {OUTPUT_OCR}  ({len(df)} rows, OCR-grouped)")


if __name__ == "__main__":
    main()
